print('привет')
b = input('введи своё имя')
print('привет')
a = int(input('Сколько будет 10-2'))
print('a')
s = input('сколько время?')
print('сейчас')
for i in range:
    print('fkjas')
print('Пока')
